version: 2

models:
  - name: stg_addresses
    description: Address information including state, country, zip code. 
    columns:
      - name: address_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
      - name: address
      - name: zipcode
        #tests:
        #- numeric_only
      - name: state
      - name: country


  - name: stg_events
    description: Includes information on the events of each online order.
    columns:
      - name: event_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
      - name: session_id
      - name: user_id
          - not_null
      - name: page_url
      - name: created_at
      - name: event_type
      - name: order_id
      - name: product_id


      
  - name: stg_order_items
    description: Includes information on products and quantity in each order.
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - not_null
      - name: product_id
          - not_null
      - name: quantity
        #tests:
        #- numeric_only


  -  name: stg_orders
     description: Includes information on each order like user, order and shipping details.
     columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
      - name: user_id
      - name: promo_id
      - name: address_id
      - name: created_at_utc
      - name: order_cost
      - name: shipping_cost
      - name: order_total
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status

  -  name: stg_products
     description: Includes information on each product like price and inventory.
     columns:
     - name: product_id
       description: "The primary key for this table"
       tests:
          - not_null
          - unique
     - name: name
     - name: price
     - name: inventory


  -  name: stg_promos
     description: Includes promotional information for products.
     columns:
     - name: promo_id
       description: "The primary key for this table"
       tests:
          - not_null
          - unique
     - name: discount
     - name: status

  -  name: stg_users
     description: Includes information on users include name, email, etc.
     columns:
     - name: user_id
       description: "The primary key for this table"
       tests:
          - not_null
          - unique
     - name: first_name
     - name: last_name
     - name: email
     - name: phone_number
     - name: created_at_utc
     - name: updated_at_utc 