version: 2

products:
    tables:
      - name: fct_page_view
        description: Includes session activity where the event was a page view.
        columns:
        - name: page_view_id
          description: This is the primary key for this table.
          tests:
          - not_null
          - unique
        - name: session_id
          tests:
            - not_null
        - name: user_id
        - name: page_url
        - name: created_at_utc
        - name: order_id
        - name: product_id

      - name: fct_user_sessions
        description: Includes session details for users first & last sessions.
        columns:
        - name: session_id
          tests:
            - not_null
            - unique
        - name: user_id
        - name: session_length
        - name: first_event_type
        - name: last_event_type

      - name: int_sessions_timing
        description: Identifies users first and last event time in the session.
        columns:
        - name: session_id
        - name: last_session_event_time
        - name: last_session_event_time
