version: 2

marketing:
    tables:      
      - name: fct_events
        description: Includes details on each 
        comlumns:
          - name: event_id
          - name: session_id
          - name: user_id
          - name: created_at_utc
          - name: order_id
          - name: product_id
          - name: product_name
          - name: price
          - name: inventory
          - name: event_type